### ISSUE TITLE
Assertion containsDocument isn't working correctly with not: true

### ISSUE THREAD

**Issue by brutus333** [helm-unittest/helm-unittest#173]
Hello @quintush : I encountered the same problem on 0.3.3 as reported in #145 - so I looked through the code a bit and I manage to fix it by reversing successful status when context is negative:

        if context.Negative {
                validateSuccess = !validateSuccess
        }
But maybe there's a better way to fix it - I don't understand completely the code.

**Comment by quintush** [comment]
Hello @brutus333,

Thanks for the feedback.

Was already in the process to refactor this assertion, as it still does not have a strict validation (checks if at least one document is correct, instead of each document), like the other assertions.

With the refactor #167 should also be fixed. 

Greetings,
@quintush
