### ISSUE TITLE
Snapshot with Jsonpath using array filtering with more than 1 element

### ISSUE THREAD

**Issue by lucasoares** [helm-unittest/helm-unittest#289]
I'm trying to create an assert to match the snapshot of an filtered array.

My path selector is a valid json path filtering all elements of an array with specific regex evaluation, but the result snapshot contains only the first match:

![image](https://github.com/helm-unittest/helm-unittest/assets/10624972/2ad1d718-e8b4-4a8b-a599-90b8ba3fa8f7)

Test assert:

```yaml
      - matchSnapshot:
          path: spec.template.spec.containers[0].env[?(@['name']=~/OTEL_.+/)]
```

Snapshot result:

![image](https://github.com/helm-unittest/helm-unittest/assets/10624972/3c5513a6-8e24-456c-935e-30511fd1b4d2)

Is there any workaround for this?

**Comment by dragonpil** [comment]
I haveth general issue where the path only accepts one value. When I provide a JSONPath expression that results in an array, only one element is considered. Is there a workaround for testing something like 'contains in all objects of an array'?

**Comment by ivankatliarchuk** [comment]
Without reproducible example quite tricky to work on a fix

**Comment by dragonpil** [comment]
> Without reproducible example quite tricky to work on a fix

Agree I will provide you an small reproducer

**Comment by quintush** [comment]
Hello @lucasoares, @dragonpil, @ivankatliarchuk 

With the addition on jsonPath expressions, I started to limit all assertions to a single result.
This to keep the original behaviour similar and to ensure I don't  create false positives or other errors.

During the update of all assertions it seems I forgot to validate and return an error when more than 1 result is found.
Instead of adding the additional validation, I'm planning to enhance the assertions to allow multiple paths.

Greetings,
@quintush
