### ISSUE TITLE
helm-unittest uses different resource ordering than helm

### ISSUE THREAD

**Issue by raxod502-plaid** [helm-unittest/helm-unittest#303]
Given https://github.com/helm-unittest/helm-unittest/issues/302, it is still necessary to use `documentIndex` to select a document from a multi-manifest helm chart. However, this feature is very difficult to use, because the order of resources used by helm-unittest is totally different from the one used by helm (in e.g. `helm template`).

helm-unittest uses the order of resources exactly as they are specified in the helm chart template files. While helm sorts them [according to a hardcoded list of kinds](https://github.com/helm/helm/blob/c309b6f0ff63856811846ce18f3bdc93d2b4d54b/pkg/releaseutil/kind_sorter.go#L31-L68) and there is no way to override this, making it difficult to determine the current `documentIndex` to use, except by guess-and-check or mentally expanding the templates without use of helm.

So for example if you want to write an assertion against resource X in your helm chart, and you run `helm template` to determine that resource X appears at index 5, say, then when you write a helm-unittest spec with `documentIndex: 5` it will probably fail because the assertion is run against some other random resource instead.

**Comment by ivankatliarchuk** [comment]
Hi, any examples to reproduce?

**Comment by ivankatliarchuk** [comment]
Yeah it's a bug. The fill may effect a decent number of helm charts under tests.
Snapshot test example
```
---yml
suite: issue 303 for helm-unittest
tests:
- it: manifest should match snapshot
  asserts:
    - matchSnapshot: {}
```

Snapshot output
```snap
manifest should match snapshot:
  1: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: example-deployment
  2: |
    apiVersion: v1
    kind: Service
    metadata:
      name: example-service
```

Ordering is not right.

**Comment by quintush** [comment]
Hello @raxod502-plaid,

The ordering of the helm-chart unittest rendered output is alphabetical.
This is a design choice for the following reason.

Where helm is generating in an static order so resources are properly deployed, the helm-unittest does no deployments.
Therefore the helm-unittest does not have the static order.

Also when there are multiple the same types (e.g. deployments), the helm template can generate the same types in a different order. In helm-unittest the order has to be always te same, otherwise we will have problems with:
- documentIndex (as you identified)
- snapshots (as different orders result in different snapshots).

There where previous issues related to inconsistent ordering (#149, #179). 
This was one of the reasons to develop the documentSelector for those charts where the index of resources is less predictable.


When you need to identify an index value, it is better to use the snapshot feature to identify the outcome and the index order.

Greetings,
@quintush

**Comment by raxod502-plaid** [comment]
That makes sense, I was unaware of the existence of the snapshot feature. It would have been helpful for that to be documented in the section that explained how to use `documentIndex`, since given the ordering issues, you can't really use `documentIndex` correctly without also relying on the snapshot feature.

But either way, `documentSelector` is better in every way, so there is no real need to support `documentIndex` given that `documentSelector` supports multiple tests per https://github.com/helm-unittest/helm-unittest/issues/302.
