### ISSUE TITLE
Snapshots with more than 1 element are non-functional

### ISSUE THREAD

**Issue by bushong1** [helm-unittest/helm-unittest#345]
I have a file that creates more than one document separated by `---`.  In this case, running a snapshot on that file will only snapshot element 0.  The docs say the default `documentIndex` is `-1`, but that appears to not be the case for snapshots. If i update the test to explicitly set either `-1` or `0`, my snapshots are identical. If i update it to be `1`, it will use the values from the 1st element (as expected).

Is there any way to configure a snapshot to use all elements of a multi document file?

**Comment by ivankatliarchuk** [comment]
Share a reproducible example please

**Comment by quintush** [comment]
Hello @bushong1, @ivankatliarchuk 

With the addition on jsonPath expressions, I started to limit all assertions to a single result.
This to keep the original behaviour similar and to ensure I don't  create false positives or other errors.

During the update of all assertions it seems I forgot to validate and return an error when more than 1 result is found.
Instead of adding the additional validation, I'm planning to enhance the assertions to allow multiple paths.

Greetings,
@quintush
